### ISSUE TITLE
Rename `overpass/*` to `overpass/*.overpassql`

### ISSUE THREAD

**Issue by FloEdelmann** [metaodi/equalstreetnames-winterthur#1]
`*.overpassql` is now the recommended file extension for Overpass QL: [OSM Wiki: Overpass QL § File extension](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#File_extension)
*(**Disclaimer:** I added that section after [some discussion](https://wiki.openstreetmap.org/wiki/Talk:Overpass_API/Overpass_QL#Recommended_file_extension?).)*

I propose to rename all Overpass QL files in this repo to `*.overpassql` for consistency.

Context: GitHub's syntax highlighting engine requires that 200 repositories use the same file extension before they consider supporting that syntax and file extension: https://github.com/github/linguist/issues/5890

---

See also this upstream issue: https://github.com/EqualStreetNames/equalstreetnames/issues/619

**Comment by FloEdelmann** [comment]
@metaodi Would a PR be accepted?

**Comment by metaodi** [comment]
I changed the file extensions in the overpass directory, so all done.

**Comment by FloEdelmann** [comment]
Event better, thank you! :slightly_smiling_face:

**Comment by FloEdelmann** [comment]
For reference: https://github.com/metaodi/equalstreetnames-winterthur/commit/1723d09fdd29cd6424b819cea8efc405fb6c2e74 and https://github.com/metaodi/equalstreetnames-winterthur/commit/389512e79f7bd9e0eecc0d5d99551dd74efee8db
